Integrate Swagger and add migration files
lvthang1606/java-spring pull request #1
Opened 2023-03-02 09:40 UTC by lvthang1606

- [ ] Add an empty API (eg GET api/v1/books)
- [ ] Add library
- [ ] Check the Swagger UI and make sure it works correctly
- [ ] Add migration files to create the database tables following the requirement

2023-03-02 09:49 UTC, nguyenvanman requested changes

2023-03-02 09:49 UTC, nguyenvanman commented on src/main/java/com/thangle/persistence/book/BookStore.java
> +        List<Book> books = toBooks(toList(bookRepository.findAll()));
```suggestion
        return toBooks(toList(bookRepository.findAll()));
```

2023-03-02 09:49 UTC, nguyenvanman commented on src/main/java/com/thangle/api/book/BookController.java
> +    private final BookService bookService;
Please add unit-tests for controller, service, store and mappers

2023-03-02 09:49 UTC, nguyenvanman commented on src/main/java/com/thangle/persistence/book/BookEntity.java
> +    public static final String ID_FIELD = "id";
Redundant, right?

2023-03-02 09:58 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/book/BookEntity.java
> +    public static final String ID_FIELD = "id";
Ok to keep it

2023-03-03 03:49 UTC, nguyenvanman approved these changes

2023-03-03 08:07 UTC, merged