Create CRUD for users
lvthang1606/java-spring pull request #3
Opened 2023-03-08 03:58 UTC by lvthang1606

2023-03-08 10:19 UTC, nguyenvanman requested changes

2023-03-08 10:19 UTC, nguyenvanman commented on src/main/java/com/thangle/domain/user/UserService.java
> +        findUserById(id);
Mục đích gọi hàm này là gì?

2023-03-08 11:10 UTC, lvthang1606 commented on src/main/java/com/thangle/domain/user/UserService.java
> +        findUserById(id);
Để nó trả lỗi HttpStatus.NOT_FOUND nếu không tìm ra id của user cần delete á anh

2023-03-09 02:50 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        user.setUsername(updatedUser.getUsername());
Nếu user đổi user trùng với một người dùng khác thì sao

2023-03-09 02:50 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        user.setPassword(updatedUser.getPassword());
Nếu người dùng không nhập mật khẩu thì mật khẩu cũ bị xoá?

2023-03-09 02:51 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        findUserById(id);
Trong trường hợp đó

```java
final User user = findUserById(id);
userStore.deleteUser(user.getId());
```

2023-03-09 02:52 UTC, voquanghoa commented on src/main/java/com/thangle/error/ValidationException.java
> +    public ValidationException(final HttpStatus httpStatus, final String message, Object... args) {
Cái này luôn là HTTP STATUS 400

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/api/user/UserController.java
> +    public UserDTO findUserById(final @PathVariable UUID id) {
```suggestion
    public UserDTO findById(final @PathVariable UUID id) {
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/api/user/UserController.java
> +    public UserDTO createUser(final @RequestBody User user) {
```suggestion
    public UserDTO create(final @RequestBody User user) {
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/api/user/UserController.java
> +    public UserDTO updateUser(final @PathVariable UUID id, final @RequestBody UserDTO userDTO) {
```suggestion
    public UserDTO update(final @PathVariable UUID id, final @RequestBody UserDTO userDTO) {
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/api/user/UserController.java
> +    public void deleteUser(final @PathVariable UUID id) {
```suggestion
    public void delete(final @PathVariable UUID id) {
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/api/user/UserDTO.java
> +    private String password;
We won't response user's password to client. Even return null. We should remove the field to the model

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +    public User findUserById(final UUID id) {
```suggestion
    public User findById(final UUID id) {
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        if (updatedUser.getPassword() == null || updatedUser.getPassword().toString() == "") {
Use `isBlank` from `StringUtils`

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        verifyUsernameAvailable(updatedUser.getUsername());
This line
```java
verifyUsernameAvailable(updatedUser.getUsername());
```

and 
```java
user.setUsername(updatedUser.getUsername());
```

are related together, should gather them

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        user.setPassword(updatedUser.getPassword());
Didn't fixed?

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        final Optional<User> optionalUser = userStore.findUserByUsername(username);
This give the error is user doesn't want to changes their username

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +            throw new BadRequestException("User already exists");
```suggestion
            throw new BadRequestException("The username %s already exists", optionalUser.get().getUsername());
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/user/UserStore.java
> +    public Optional<User> findUserById(final UUID id) {
```suggestion
    public Optional<User> findById(final UUID id) {
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/user/UserStore.java
> +    public Optional<User> findUserByUsername(final String username) {
```suggestion
    public Optional<User> findByUsername(final String username) {
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/user/UserStore.java
> +    public User createUser(final User user) {
```suggestion
    public User create(final User user) {
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/user/UserStore.java
> +    public User updateUser(final User updatedUser) {
```suggestion
    public User update(final User updatedUser) {
```

2023-03-13 04:32 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/user/UserStore.java
> +    public void deleteUser(final UUID id) {
```suggestion
    public void delete(final UUID id) {
```

or `deleteById`

2023-03-13 04:32 UTC, voquanghoa commented on src/test/java/com/thangle/api/user/UserControllerTest.java
> +    void shouldCreateUser_OK() throws Exception{
Don't forget to rename them all after renaming method from implementation

```suggestion
    void shouldCreate_OK() throws Exception{
```

2023-03-13 04:32 UTC, voquanghoa commented on src/test/java/com/thangle/api/user/UserControllerTest.java
> +        when(userService.updateUser(any(UUID.class), any(User.class))).thenReturn(updatedUser);
```suggestion
        when(userService.updateUser(any(), any())).thenReturn(updatedUser);
```

When the overload issue doesn't happens, no need to pass the class name

2023-03-13 04:32 UTC, voquanghoa commented on src/test/java/com/thangle/domain/user/UserServiceTest.java
> +
Annotation is a part of thedeclarion (event class, method, field ...) so don't put empty line here

2023-03-13 07:08 UTC, lvthang1606 commented on src/main/java/com/thangle/domain/user/UserService.java
> +        user.setPassword(updatedUser.getPassword());
Em có thêm lệnh check password trước rồi á anh
<img width="710" alt="Screen Shot 2023-03-13 at 2 07 42 PM" src="https://user-images.githubusercontent.com/51842821/224631118-45881d41-d686-4525-b69e-65fac097fe2f.png">

2023-03-13 09:27 UTC, lvthang1606 commented on src/main/java/com/thangle/domain/user/UserService.java
> +        if (updatedUser.getPassword() == null || updatedUser.getPassword().toString() == "") {
Dùng hàm isBlank() thì value phải không null á anh
<img width="913" alt="Screen Shot 2023-03-13 at 4 22 38 PM" src="https://user-images.githubusercontent.com/51842821/224660214-3bff9057-1b64-4730-bcff-153d6324a50d.png">
Nên em sửa thành như ri: updatedUser.getPassword() == null || updatedUser.getPassword().isEmpty()
Anh xem giúp em như rứa có được không anh nha

2023-03-13 09:33 UTC, voquanghoa approved these changes

2023-03-13 09:52 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        if (updatedUser.getPassword() == null || updatedUser.getPassword().toString() == "") {
Nó như ri

```
import static org.apache.commons.lang3.StringUtils.isBlank;
```

Và

```java
if (!isBlank(updatedUser.getPassword())) {
   ...
```

2023-03-13 10:08 UTC, merged