Create CRUD for books
lvthang1606/java-spring pull request #4
Opened 2023-03-14 09:54 UTC by lvthang1606

2023-03-15 03:53 UTC, nguyenvanman requested changes

2023-03-15 03:53 UTC, nguyenvanman commented on src/main/java/com/thangle/api/book/BookController.java
> +    public BookDTO create(final @RequestBody Book book) {
RequestBody must be a DTO

2023-03-15 03:53 UTC, nguyenvanman commented on src/main/java/com/thangle/api/book/BookController.java
> +    public BookDTO update(final @PathVariable UUID id, final @RequestBody BookDTO bookDTO) {
Please create another DTO for RequestBody since we won't use all of the fields in BookDTO (e.g createdAt, updatedAt, ...)

2023-03-15 03:53 UTC, nguyenvanman commented on src/main/java/com/thangle/domain/role/RoleService.java
> +public class RoleService {
Is this redundant?

2023-03-15 04:00 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookDTOMapper.java
> +                .updatedAt(bookDTO.getUpdatedAt())
These values with be calculated by backend, not from frontend

2023-03-15 04:01 UTC, nguyenvanman requested changes

2023-03-15 04:01 UTC, nguyenvanman commented on src/main/java/com/thangle/domain/role/RoleError.java
> +public class RoleError {
Is this redundant?

2023-03-15 04:01 UTC, nguyenvanman commented on src/main/java/com/thangle/domain/role/Role.java
> +public class Role {
Is this redundant?

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookDTOMapper.java
> +                .id(bookDTO.getId())
We don't use this value because
- When create a new book --> we don't have it
- When update a book --> we use id from path

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +    public void verifyBookTitleAvailable(final String title) {
Dont need to validate this. It's fine to have the books same title

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        verifyInputData(book);
More clear `validateBook`

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        verifyBookTitleAvailable(book.getTitle());
Remove this line

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +    private void verifyInputData(final Book book) {
Move this method to a validation class eg BookValidation

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        if (isBlank(String.valueOf(book.getUserId()))) {
```suggestion
        if (book.getUserId() == null) {
```

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        if (isBlank(String.valueOf(updatedBook.getId()))) {
We use `final UUID id,`

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        book.setId(updatedBook.getId());
This line is redundant

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        return bookStore.create(book);
Specify the createTime

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/role/Role.java
> +public class Role {
Remove

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/role/RoleError.java
> +public class RoleError {
Remove

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        if (isBlank(updatedUser.getPassword())) {
Dont include the unrelated changes in this PR

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/role/RoleEntityMapper.java
> +public class RoleEntityMapper {
Remove

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/role/RoleRepository.java
> +public interface RoleRepository {
Remove

2023-03-15 04:07 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/role/RoleStore.java
> +public class RoleStore {
Remove

2023-03-15 04:51 UTC, nguyenvanman requested changes

2023-03-15 04:51 UTC, nguyenvanman commented on src/test/java/com/thangle/persistence/book/BookStoreTest.java
> +        assertEquals(actual.getId(), expected.getId());
Please put expected as the first param of assert methods, and actual as the second one. Do this for all assertions

2023-03-15 05:21 UTC, tleviet commented on src/main/java/com/thangle/api/book/BookController.java
> +    @GetMapping("{id}")
- [x] add thêm api search books với những fields khác nữa e

2023-03-15 05:21 UTC, tleviet commented on src/main/java/com/thangle/domain/book/BookService.java
> +    public void verifyBookTitleAvailable(final String title) {
- [x] can be verify both book title and author?
cc @voquanghoa

2023-03-15 05:21 UTC, tleviet commented on src/main/java/com/thangle/persistence/book/BookEntity.java
>  }
- [x] ID_FIELD is redundant?

2023-03-15 05:21 UTC, tleviet commented on src/test/java/com/thangle/persistence/book/BookStoreTest.java
> +        bookStore.deleteById(book.getId());
- [x] add more blank line

2023-03-15 05:21 UTC, tleviet commented on src/test/java/com/thangle/persistence/book/BookStoreTest.java
> +        final var book = buildBookEntity();
- [x] add more blank line at the below

2023-03-15 14:15 UTC, lvthang1606 commented on src/main/java/com/thangle/domain/user/UserService.java
> +        if (isBlank(updatedUser.getPassword())) {
Should I create another PR including these changes in it, please?

2023-03-15 16:43 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        if (isBlank(updatedUser.getPassword())) {
Yes. It's better

2023-03-16 07:57 UTC, tleviet commented on src/main/java/com/thangle/domain/book/BookService.java
> +        verifyTitleAndAuthorAvailable(updatedBook);
- [ ] verify available ở api update giống với api create lun ah e? e thử check api update book này lại nhé?

2023-03-16 07:57 UTC, tleviet commented on src/main/java/com/thangle/persistence/book/BookRepository.java
> +    List<BookEntity> find(final String searchTerm);
- [ ] check lại value của @Query e nhé, e thử request api search này có response data hông?

2023-03-16 07:57 UTC, tleviet commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        when(bookService.find(anyString())).thenReturn(expected);
- [ ] nên dùng author hoặc title của book (remove anyString()) e

2023-03-16 07:57 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +    void shouldFindById_OK() throws Exception {
- [ ] add thêm test cho api Find books by title, author or description e

2023-03-16 07:57 UTC, tleviet commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        when(bookStore.create(book)).thenReturn(book);
- [ ] test này ko thấy verify title và author e hè :thinking: ?

2023-03-16 07:57 UTC, tleviet commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +    void shouldUpdate_OK() {
- [ ] test này ko thấy verify title và author e hè :thinking: ?

2023-03-16 07:58 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
- [ ] Refactor thêm chỗ này e:
- Step 1. Tạo class AbstractControllerTest
- Step 2. Tạo hàm `get(final String path)` và `post(final String path, final Object body)` ... tương tự cho put, delete
- Step 3. Cho BookControllerTest kế thừa AbstractControllerTest và dùng mấy hàm kia

cc @voquanghoa

2023-03-16 08:59 UTC, lvthang1606 commented on src/main/java/com/thangle/persistence/book/BookRepository.java
> +    List<BookEntity> find(final String searchTerm);
Trước khi push lên em có check rồi á anh.. nó works oke anh 
<img width="1414" alt="Screen Shot 2023-03-16 at 3 58 08 PM" src="https://user-images.githubusercontent.com/51842821/225565762-a3ec9f30-05b3-42b8-9c8d-cd3b6f9ce9f5.png">

2023-03-16 09:22 UTC, tleviet commented on src/main/java/com/thangle/persistence/book/BookRepository.java
> +    List<BookEntity> find(final String searchTerm);
ok e, search thử book khác vẫn ok e hả? thấy câu query ko có space giữa các điều kiện

2023-03-16 16:50 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookDTO.java
> +    private Instant updatedAt;
Class này gây confuse với `BookUpdateDTO`. Đổi thành `BookResponseDTO`

2023-03-16 16:50 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookController.java
> +    public BookDTO create(final @RequestBody BookDTO bookDTO) {
Mình không dùng `BookDTO` cho request vì nó dư id, createAt, updateAt

2023-03-16 16:50 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookUpdateDTO.java
> +    private UUID id;
Không lấy id ở đây vì id bookUpdate đã có ở path `{id}`, ở đây thêm nữa sẽ gây nhập nhằng

2023-03-16 16:50 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookUpdateDTOMapper.java
> +                .id(bookUpdateDTO.getId())
```suggestion
```

2023-03-16 16:50 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        if (!books.isEmpty()) {
```suggestion
        if (books.isPresent()) {
```

2023-03-16 16:50 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/book/BookRepository.java
> +    List<BookEntity> find(final String searchTerm);
Thử đổi chữ hoa chữ thường xem

2023-03-16 16:50 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        mvc.perform(MockMvcRequestBuilders.put(BASE_URL + "/" + bookNeedsToBeUpdated.getId())
Mấy đoạn code này bị giống nhau, như comment trên https://github.com/lvthang1606/java-spring/pull/4/files#r1138254184

2023-03-16 16:50 UTC, voquanghoa commented on src/test/java/com/thangle/fakes/BookFakes.java
> +                .createdAt(Instant.EPOCH)
Đổi thành `Instant.now()` ở đây và những ở chỗ khác

2023-03-17 06:30 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +    private void verifyTitleAndAuthorAvailable(final Book book, final UUID id, final Activity activity) {
Tách làm 2 hàm thì dễ hơn

2023-03-17 06:50 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookChangeDTO.java
> +public class BookChangeDTO {
```suggestion
public class BookUpdateDTO {
```

2023-03-17 06:50 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookChangeDTOMapper.java
> +public class BookChangeDTOMapper {
```suggestion
public class BookUpdateDTOMapper {
```

2023-03-17 06:50 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookController.java
> +    public BookChangeDTO create(final @RequestBody BookChangeDTO bookChangeDTO) {
```suggestion
    public BookResponseDTO create(final @RequestBody BookChangeDTO bookChangeDTO) {
```

2023-03-17 06:50 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookDTOMapper.java
> +    public static List<BookResponseDTO> toBookDTOs(final List<Book> books) {
```suggestion
    public static List<BookResponseDTO> toBookResponseDTOs(final List<Book> books) {
```

2023-03-17 06:50 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        verifyTitleAndAuthorAvailable(book, book.getId(),Activity.CREATE);
```suggestion
        verifyTitleAndAuthorAvailable(book, book.getId(), Activity.CREATE);
```

2023-03-17 06:50 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookValidation.java
> +        }
Tách làm 3 hàm rồi gọi

2023-03-17 06:50 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/AbstractControllerTest.java
> +    private final ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());
```suggestion
    private static final ObjectMapper mapper = new ObjectMapper().registerModule(new JavaTimeModule());
```

2023-03-17 06:50 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/AbstractControllerTest.java
> +        return mockMvc.perform(MockMvcRequestBuilders.delete(path).contentType(MediaType.APPLICATION_JSON));
Refactor thêm

2023-03-17 06:50 UTC, voquanghoa commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        when(bookStore.create(book)).thenReturn(book);
không cần cũng được

2023-03-17 06:50 UTC, voquanghoa commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        });
```suggestion
        assertThrows(BadRequestException.class, () ->    bookService.create(book));
```

2023-03-17 06:50 UTC, voquanghoa commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        });
```suggestion
       assertThrows(NotFoundException.class, () -> bookService.update(bookToUpdate.getId(), bookToUpdate));
```

2023-03-17 07:33 UTC, tleviet commented on src/main/java/com/thangle/api/book/BookController.java
> +    public BookChangeDTO create(final @RequestBody BookChangeDTO bookChangeDTO) {
- [x] sao trả về `BookResponseDTO` ở đây lun e?

2023-03-17 07:33 UTC, tleviet commented on src/main/java/com/thangle/persistence/book/BookRepository.java
> +    List<BookEntity> find(final String searchTerm);
- [x] @lvthang1606 check comment a Hoà lun nhé

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.update(any(), any())).thenReturn(updatedBook);
- [ ] book update cần đưa thông tin gì mình cần update e (hạn chế dùng any(), any())

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        final var actual = bookService.find(book.getTitle());
- [x] kiểm tra lại test này đúng chưa e? 2 dòng này sao giống nhau vậy 🤔

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        when(bookStore.create(book)).thenReturn(book);
- [x] check comment phía trên của a lun hỉ

2023-03-17 07:33 UTC, tleviet commented on src/main/java/com/thangle/persistence/book/BookRepository.java
> +    List<BookEntity> findByTitleAndAuthor(final String title, final String author);
- [x] Nên trả về 1 BookEntity thôi e, vì mình đâu cho tạo trùng

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        final var expected = buildBooks();
- [x] sao mình cần đến 2 biến này lun e, có khi nào title ở book khác với title ở expected ko e 🤔 ?

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        final var updatedBook = buildBook();
- [x] 2 biến này cùng là `buildBook()` có khác chi ko e 🤔 ?

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        assertThrows(NotFoundException.class, () -> bookService.update(bookToUpdate.getId(), bookToUpdate));
- [ ] test này là sao e 🤔 ?

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        final var updatedBook = buildBook();
- [ ] 2 biến này khác nhau gì vậy e? sao ko dùng 1 biến thôi 🤔

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/persistence/book/BookStoreTest.java
> +        when(bookRepository.save(any())).thenReturn(expected);
- [ ] hạn chế dùng `any()` e, sửa cho những chỗ khác lun e

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/api/book/AbstractControllerTest.java
> +public abstract class AbstractControllerTest {
- [ ] abstract controller này có dùng được cho UserControllerTest ko e?

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
- [ ] Cho BookControllerTest, UserControllerTest kế thừa AbstractControllerTest và dùng mấy hàm kia e

2023-03-17 07:33 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
- [ ] unit test ở class này bị failed e nhé

2023-03-17 07:45 UTC, lvthang1606 commented on src/main/java/com/thangle/domain/book/BookService.java
> +        if (!books.isEmpty()) {
Kiểu List<E> nó không có hàm isPresent(), em search thêm hàm isPresent() cho List<E> mà cũng không có á anh

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookResponseDTO.java
> +public class BookResponseDTO implements ResponseDTO {
Tại sao cần phải implement interface này?

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookResponseDTOMapper.java
> +    public static Book toBook(final BookResponseDTO bookResponseDTO) {
Hàm này dùng để làm gì?

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookUpdateDTO.java
> +public class BookUpdateDTO implements UpdateDTO {
Tại sao phải có implement class kia

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookUpdateDTOMapper.java
> +    public static Book toBook(final BookUpdateDTO bookUpdateDTO) {
Thêm dòng trống ngay sau dòng khai báo class

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/api/book/BookUpdateDTOMapper.java
> +    public static BookUpdateDTO toBookUpdateDTO(final Book book) {
Tại sao phải có cái này

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/api/user/UserDTO.java
> +public class UserDTO implements ResponseDTO, UpdateDTO {
Bỏ phần implements này đi,

Và làm 1 PR sửa cái này. Không được phép response user về client

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/common/ResponseDTO.java
> +public interface ResponseDTO {
interface rỗng thì không để làm gì cả

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/common/UpdateDTO.java
> +public interface UpdateDTO {
interface rỗng thì không để làm gì cả

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +    private void verifyTitleAndAuthorAvailable(final Book book, final UUID id, final Activity activity) {
Sửa check Resolve mà không fix?

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        verifyTitleAndAuthorAvailable(book, book.getId(),Activity.CREATE);
KHÔNG fix?

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookService.java
> +        verifyTitleAndAuthorAvailable(updatedBook, id, Activity.UPDATE);
không có cái này cũng được

2023-03-17 10:24 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookValidation.java
> +    private void validateUserId(final UUID id) {
```suggestion
    private void validateUserId(final UUID userId) {
```

2023-03-17 10:24 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/AbstractControllerTest.java
> +    public ResultActions resultActions(final MockHttpServletRequestBuilder builder) throws Exception {
Tên hàm phải là một động từ miêu tả công việc đang làm. Hàm này chỉ dùng trong nội bộ class nên phải để là private

```suggestion
    private ResultActions resultActions(final MockHttpServletRequestBuilder builder) throws Exception {
```

2023-03-17 10:24 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/AbstractControllerTest.java
> +    }
Mình chỉ cho các lớp unit test sử dụng các method này nên phải khai báo là protected

2023-03-17 10:24 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/AbstractControllerTest.java
> +package com.thangle.api.book;
```suggestion
package com.thangle.api;
```

2023-03-17 10:24 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/AbstractControllerTest.java
> +    public ResultActions put(final String path, final UpdateDTO updateDTO) throws Exception {
```suggestion
    public ResultActions put(final String path, final Object body) throws Exception {
```

2023-03-17 10:24 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/AbstractControllerTest.java
> +    public ResultActions post(final String path, final ResponseDTO responseDTO) throws Exception {
```suggestion
    public ResultActions post(final String path, final Object body) throws Exception {
```

2023-03-17 10:24 UTC, voquanghoa commented on src/test/java/com/thangle/fakes/BookFakes.java
> +                .id(UUID.fromString("56bb3be9-c0f2-45a1-b695-6bd9266d8d78"))
Tại sao không thể random?

2023-03-19 14:21 UTC, lvthang1606 commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.update(any(), any())).thenReturn(updatedBook);
Khi em truyền thông tin cụ thể vào, ví dụ như này: 
`when(bookService.update(bookNeedsToBeUpdated.getId(), updatedBook)).thenReturn(updatedBook);`
Thì hàm thenReturn luôn luôn trả về null, em có debug và thử nhiều cách nhưng vẫn không sửa được chỗ này.
Có bài viết này có vẻ là mô tả đúng lỗi em đang gặp nhất, em có thử fix theo cách họ bày nhưng cũng không được: _https://stackoverflow.com/questions/33124153/mockito-nullpointerexception-when-stubbing-method_
2 anh có solution gì không? Chỉ em với ạ @voquanghoa @tleviet

2023-03-20 03:34 UTC, tleviet commented on src/main/java/com/thangle/domain/book/BookValidation.java
> +            throw new BadRequestException("User cannot be empty");
- [x] `cannot be null` chứ e

2023-03-20 03:34 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        final var actual = bookService.find(book.getTitle());
- [x] dòng này để làm gì e?

2023-03-20 03:34 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.create(any())).thenReturn(book);
- [ ] hạn chế dùng `any()` e

2023-03-20 03:34 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.update(any(), any())).thenReturn(updatedBook);
- [x] e debug thì method buildBook() của e value là gì? 
nếu chưa fix dc tạm thời e dùng đỡ any with class type là gì ở tham số thứ 2 thôi, tham số đầu tiên nên dùng book id nhé (ko dùng `any()`) 

cc @voquanghoa

2023-03-20 03:34 UTC, tleviet commented on src/main/java/com/thangle/domain/book/BookService.java
> +        validateBook(updatedBook);
- [ ] chỗ method update sao vẫn giống create e hè 🤔? a nhớ có comment chỗ duplicate khác validate với create book mà

2023-03-20 03:34 UTC, tleviet commented on src/main/java/com/thangle/persistence/book/BookRepository.java
> +    List<BookEntity> find(final String searchTerm);
- [x] `LOWER( CONCAT(...)` chỗ xoá space giữa hàm LOWER và CONCAT e

2023-03-20 03:34 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookResponseDTOMapperTest.java
> +    @Test
- [x] thêm dòng trống phía trên e, để ý mấy file khác lun e

2023-03-20 03:34 UTC, tleviet commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        final var expected = bookService.update(book.getId(), updatedBook);
- [x] sao ở đây lại là expected e 🤔 ?

2023-03-20 03:34 UTC, tleviet commented on src/test/java/com/thangle/fakes/BookFakes.java
> +
- [x] xoá bớt dòng trống e

2023-03-20 03:34 UTC, tleviet commented on src/test/java/com/thangle/persistence/book/BookStoreTest.java
> +        final var actual = bookStore.update(buildBook());
- [x] thêm dòng trống phía dưới e

2023-03-20 04:40 UTC, lvthang1606 commented on src/main/java/com/thangle/domain/book/BookService.java
> +        validateBook(updatedBook);
Hàm validateBook này là em check mấy field trong đó có bị null không thôi anh, nên là giống nhau giữa update và create, còn hàm verify title với author anh Hoà nói không cần nên em bỏ rồi

2023-03-20 04:42 UTC, lvthang1606 commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.create(any())).thenReturn(book);
Chỗ này em cũng gặp lỗi tương tự với comment phía trên của em á anh 🥹

2023-03-20 04:55 UTC, lvthang1606 commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.update(any(), any())).thenReturn(updatedBook);
Method buildBook() của em có value được tạo ra từ BookFakes (đoạn này đúng expected), nhưng sau khi nó chạy đến hàm thenReturn(...) thì value book đó lại thành null anh 😭

2023-03-20 06:42 UTC, voquanghoa commented
Tìm các comment cũ, click Resolve vào các comment đã fix

2023-03-20 06:49 UTC, voquanghoa commented on src/main/java/com/thangle/domain/book/BookValidation.java
> +            throw new BadRequestException("Book's title cannot be empty");
Thiếu unit test cho các chỗ throw này

2023-03-20 06:49 UTC, voquanghoa commented on src/main/java/com/thangle/domain/user/UserService.java
> +        if (isBlank(updatedUser.getPassword())) {
Password có thể rỗng nếu người dùng không muốn đổi mật khẩu. Làm PR riêng nha

2023-03-20 06:49 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/book/BookRepository.java
> +    @Query(value = "SELECT DISTINCT * FROM books WHERE LOWER(title) LIKE LOWER(CONCAT('%', :searchTerm, '%'))" +
Book có cột ID là unique, vậy DISTINCT ở đây đâu có tác dụng gì đâu. 
Sử dụng ILIKE để câu lệnh query không phân biệt hoa thường

2023-03-20 06:49 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/book/BookStore.java
> +    }
Có thể gộp chung thành `save`

2023-03-20 06:49 UTC, voquanghoa commented on src/test/java/com/thangle/api/AbstractControllerTest.java
> +    private ResultActions performRequestBuilder(final MockHttpServletRequestBuilder builder) throws Exception {
Có thể ngắn gọn hơn


```suggestion
    private ResultActions perform(final MockHttpServletRequestBuilder builder) throws Exception {
```

2023-03-20 06:56 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.update(any(), any())).thenReturn(updatedBook);
Nó null bởi vì bên chỗ mock

```java
when(object.method(input)).thenReturn(value);
```

Đầu vào là `input` nó không thực sự giống với lúc thực tế gọi

```java
var xxx = object.method(other input)
```

từ đó việc giả lập thất bại và việc gọi hàm trên trả về null. 

Như vậy mình cần phải debug lại chỗ gọi `object.method(param)` và đảm bảo rằng

1. Việc mock bên kia đúng với object mà bên thực tế nếu gọi
2. Nếu không thể làm (1) thì có thể dùng `argThat()` để xác nhận là param thoả mãn điều kiện gì đó


Ví dụ

```java
when(object.method(x -> x % 2 == 0)).thenReturn(value);
when(object.method(x -> x.getName().endsWith("Name"))).thenReturn(value);
```

2023-03-20 07:48 UTC, lvthang1606 commented on src/main/java/com/thangle/domain/user/UserService.java
> +        if (isBlank(updatedUser.getPassword())) {
Oke anh, em gộp vô PR sau luôn anh nha

2023-03-20 08:24 UTC, voquanghoa commented on src/main/java/com/thangle/persistence/book/BookRepository.java
> +            "OR description ILIKE CONCAT('%', :searchTerm, '%')")
Nên để 1 khoảng trống ngay sau dấu `)` cuối cùng của mỗi dòng

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.find(book.getTitle())).thenReturn(Collections.singletonList(book));
```suggestion
        when(bookService.find(book.getTitle())).thenReturn(List.of(book));
```

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.create(any())).thenReturn(book);
dùng argThat

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.update(eq(bookNeedsToBeUpdated.getId()), any(Book.class))).thenReturn(updatedBook);
```suggestion
        when(bookService.update(eq(bookNeedsToBeUpdated.getId()), any())).thenReturn(updatedBook);
```

Tránh dùng any (kể cả any(Something.class))

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        book.setTitle("");
```suggestion
        final var book = buildBook().withTitle("");
```

Và những chỗ khác tương tự

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        updatedBook.setTitle("");
Đưa lệnh này lên trước
```suggestion
        updatedBook.setTitle("");
```

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        updatedBook.setAuthor("");
Same

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        final var updatedBook = buildUpdatedBook(book.getId());
```suggestion
        final var updatedBook = buildBook()
                               .withId(book.getId())
                               .withAuthor("");
```

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/domain/book/BookServiceTest.java
> +        updatedBook.setUserId(null);
Same

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/fakes/BookFakes.java
> +                .title(RandomStringUtils.randomAlphabetic(3, 10))
```suggestion
                .title(randomAlphabetic(3, 10))
```

Dùng static import (và những chỗ khác)

2023-03-20 08:24 UTC, voquanghoa commented on src/test/java/com/thangle/fakes/BookFakes.java
> +    public static Book buildUpdatedBook(UUID id) {
Cái này không cần

2023-03-20 08:35 UTC, tleviet commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.create(any())).thenReturn(book);
- [ ] vậy e có thể dùng tạm any with class type ở test controller

cc @voquanghoa

2023-03-20 08:42 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        post(BASE_URL, toBookResponseDTO(book))
```suggestion
        post(BASE_URL, toBookResponseDTO(book))
```

Chỗ này bị sai

2023-03-20 08:42 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        when(bookService.create(any())).thenReturn(book);
Vấn đề là ở đây, lệnh mock vốn dĩ được gọi không hợp lý

2023-03-20 08:44 UTC, voquanghoa commented on src/test/java/com/thangle/api/book/BookControllerTest.java
> +        put(BASE_URL + "/" + bookNeedsToBeUpdated.getId(), updatedBook)
Nhớ rằng bên controller, mình khai báo request body có kiểu là BookCreateDTO nên ở đây, tham số body cũng phải là BookCreateDTO. Do ở method `put` mình để nó là Object, IDE sẽ không báo lỗi nhưng mình vẫn phải viết cho đúng

2023-03-20 16:26 UTC, merged